version: "3.9"
services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    ports:
    - 18081:8081
    - 10251:10251
    - 10252:10252
    - 10253:10253
    - 10254:10254
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 3g
    environment:
      # Set up the /alternativenames to the name of the service in this docker-compose so that other containers can access it via https://cosmosdb:8081/... 
      AZURE_COSMOS_EMULATOR_ARGS: /enablepreview /alternativenames=cosmosdb

  busybox:
    image: alpine:3.12
    command: /bin/sh -c "/workspace/wait-for-and-trust-cosmosdb.sh"
    volumes:
    - ./scripts/client/wait-for-and-trust-cosmosdb.sh:/workspace/wait-for-and-trust-cosmosdb.sh
